# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-03 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_issue_scanresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('severity', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')])),
                ('exampleCode', models.TextField()),
                ('patch', models.TextField()),
                ('patchCode', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SecuringFunc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('issueType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securing_funcs', to='api.IssueType')),
            ],
        ),
    ]
