# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-03 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_issuetype_securingfunc'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issueType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.IssueType'),
            preserve_default=False,
        ),
    ]
