# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-03 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_issue_issuetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issueType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.IssueType'),
        ),
    ]
