# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-05 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_application_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueTypeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueName', models.CharField(max_length=20)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanTime', models.CharField(max_length=20)),
                ('totalLines', models.IntegerField(default=0)),
                ('totalFiles', models.IntegerField(default=0)),
                ('totalFolders', models.IntegerField(default=0)),
                ('totalClasses', models.IntegerField(default=0)),
                ('totalVulns', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='api.Application')),
                ('scanResult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='api.ScanResult')),
            ],
        ),
        migrations.AddField(
            model_name='issuetypecount',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_types', to='api.Summary'),
        ),
    ]
